CREATE DATABASE IF NOT EXISTS login;

USE login;

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  USER_ID NUMERIC(15),
  USERNAME VARCHAR(255) NOT NULL,
  NAME_USER VARCHAR(255) NOT NULL,
  FIRST_NAME VARCHAR(255) NOT NULL,
  USER_MAIL NVARCHAR(255) NOT NULL,
  USER_TEL NUMERIC(10) NOT NULL,
  USER_DATE_NAISS DATE,
  CONSTRAINT PK_ID PRIMARY KEY(USER_ID)
) ENGINE=InnoDB;

INSERT INTO USERS VALUES(125334, "daniVV2", "Daniel", "Vargas", "danielvargasvila09@hotmail.com", 324923429, '2000-03-18');

SELECT * FROM USERS;



